### ISSUE TITLE
Ensure coverage of mappings from SNOMED terms in DICOM to NCIt

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/operations#48]
For IDC

- [x] Review and investigate SNOMED DICOM subset that is in public domain
- [x] Assess options for programmatic query of relationships by way of mapping to public standards
- [x] Obtain any existing mappings from IDC
 

@bfurner and @DaveraGabriel assigning you two - if you aren't the right people, please reassign.

**Comment by DaveraGabriel** [comment]
Hello @nicolevasilevsky - I would like to request contact with the appropriate ICD person(s) or be directed to the appropriate ICD resource to get a listing of all SNOMED-ensconsed-in-DICOM concepts utilized by the IDC, the value sets, data collection forms or other information model / context attributes associated with these.  In the case we already have the resource, I would like to request that a data / subject matter expert be identified in order to facilitate follow-up questions that will arise as a result of completing this task. thank-you!

**Comment by nicolevasilevsky** [comment]
@DaveraGabriel it is my understanding that @volcs0 should be the single point of contact between CCDH and the nodes. @volcs0 could you help @DaveraGabriel with her request? Thanks!

**Comment by DaveraGabriel** [comment]
@nicolevasilevsky when is this due?

**Comment by nicolevasilevsky** [comment]
good question. @jmcmurry do you have any thoughts on a due date?
Maybe aim for February? I don't think it's a big task (once you have the data)

**Comment by nicolevasilevsky** [comment]
My impression was there won't be a huge number of terms, but I don't know that for sure. So I guess I don't actually know how big the task is. :)

I am also unsure how much of a priority this is, either. Hopefully @jmcmurry can advise.

**Comment by jmcmurry** [comment]
Let's aim for Feb 1 assuming that the task is not herculean. We can revisit.

**Comment by bfurner** [comment]
probably not something i have expertise or bandwidth to support here.  perhaps @mauraakush would have some bandwidth

**Comment by mellybelly** [comment]
I think @DaveraGabriel or @hsolbrig may have been looking at this already, just tagging them here.

**Comment by hsolbrig** [comment]
References:

UMLS Documentation: https://www.ncbi.nlm.nih.gov/books/NBK9676/
UMLS in general: https://www.nlm.nih.gov/research/umls/index.html
NCI Metathesaurus jump-off:  https://ncim.nci.nih.gov/ncimbrowser/

What we're looking for is the mapping from SNOMED-CT to the NCI Thesaurus NCIt using the NCI's image of the UMLS.

It is possible that this map may already be present in the NCI Enterprise Vocabulary Service (EVS) server -- don't know how many maps the NCI supports.

**Comment by gaurav** [comment]
Status update: I've found the place in the NCI Metathesaurus where SNOMED terms are mapped to NCI concepts (e.g. laterality = SNOMED CT 272741003 = NCI Metathesaurus [CUI C0332304](https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI+Metathesaurus&code=C0332304) = [NCI Thesaurus C25185](https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI%20Thesaurus&code=C25185), and have downloaded it to my computer so I can automate those mappings.

I'm currently trying to track down a list of the 7,314 SNOMED CT codes that are [licensed for use by any DICOM implementation](https://www.snomed.org/news-and-events/articles/new-global-licensing-agreement-for-snomed-ct-code), which is what I think we need to map for this issue. I haven't been able to download the SNOMED CT International or US editions from the NLM website to see if they're annotated in there, but hope to have that done sometime today. If anybody (@hsolbrig?) knows where that list is, please let me know! I'll report back on my search in a day or two.

**Comment by hsolbrig** [comment]
See: https://github.com/hsolbrig/SNOMEDToOWL/tree/master/test/data/dicom

The csv is the subset.

Output has a RF2 closure, although I never emitted the OWL for the it. Could if it would be useful


Harold Solbrig

**Comment by gaurav** [comment]
Thanks so much, Harold! All of those terms are in the NCI Metathesaurus (NCImt), as you would expect. However, only ~1,892 of those Metathesaurus concepts correspond to a NCI Thesaurus (NCIt) concept ID, so we have ~5,638 concepts left to map. If you have access to the internal project Google Drive, you can look at the mappings [as a Google Spreadsheet](https://docs.google.com/spreadsheets/d/1P1Ogzw5mhNJfrRV7FrpUjjnGNoXsg6cXtwkJFKSPG_c/edit).

Randomly clicking on the concepts that don't have an NCIt term suggests that a lot of them are varieties of animals (particularly cattle, pigs and dogs) or chemicals. In a lot of these cases, NCImt has a parent term for this term -- for example, NCIt doesn't have a term for "sphynx cat" (SNOMED CT 132680008, NCImt CUI [C1269336](https://ncim.nci.nih.gov/ncimbrowser/pages/concept_details.jsf?dictionary=NCI%20Metathesaurus&code=C1269336)), but NCImt records that this is a child term of "cat" (NCImt CUI [C0007450](https://ncim.nci.nih.gov/ncimbrowser/pages/concept_details.jsf?dictionary=NCI%20Metathesaurus&code=C0007450), NCIt [C14191](https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C14191)). I'll look into mapping those relationships and see how many more terms I can map that way.

**Comment by gaurav** [comment]
I tried using the immediate parent to fill in the remaining terms, and here are the numbers:
 - Number of terms: 7,433
 - Matched directly to NCI Thesaurus via NCI Metathesaurus concept: 1,809 (24.3%)
 - Matched indirectly via the direct parent of the NCI Metathesaurus concept: 2,188 (29.4%)
 - Could not be matched by either method: 4,807 (53.8%)

You can see the current state of the mapping [in our shared Google Drive](https://docs.google.com/spreadsheets/d/1o1FJZFYvgSwo7G0px1GTWXBijeBXpTDB6fggAOZvzJ4/edit#gid=1926810139). I'll regenerate that file later today to be a bit more readable and to include labels for the SNOMED terms, and then I'll look into figuring out how to map the remaining 54% of terms in a sensible way.

**Comment by gaurav** [comment]
I've reformatted the mapping to make it more readable; you can see it [in our shared Google Drive](https://docs.google.com/spreadsheets/d/18zrKFoLOVB4S7onJL7OC6jlsTmOD1TnGvGKgsfvbm5k/edit). I've also been looking through the terms remaining to be merged, which seem to be of mainly five kinds:
 - breeds of cattle and pigs (e.g. Lincoln red cattle breed, SNOMED 3216001)
 - chemicals (e.g. <sup>133</sup>Barium, SNOMED 3027009 -- note that this is different from standard 137-Barium, SNOMED 39290007 = NCI C61475)
 - products (e.g. Anti-heparin agent (product), SNOMED 3361000)
 - findings (e.g. Normal respiratory rhythm (finding), SNOMED 5467003)
 - qualifiers (e.g. Sessile (qualifier value), SNOMED 5712003)

We can sort the terms into these groups by looking for particular terms in the label (i.e. "finding", "qualifier", "cattle", etc.). I can't see a route for doing the mapping through another terminology in NCImt. We might need to look into other vocabularies, preferably those that already have mappings to NCIt, or maybe use something like OpenRefine to map them directly to NCIt. Is there another resource here that I'm missing?

I'd also like to get in touch with IDC and ask them for their mappings. Do you think now is a good time to do that, or should we do more work before we get in touch?

**Comment by mellybelly** [comment]
just a note that we should document two things- the metathesaurus CUI that is in between during the mapping, and then also what content should be ceded to other more authoritative resources. E.g. i don't think that cattle breeds should have NCIt as the authoritative source. We should be making recommendations back to NCIt in those cases for what they should import vs. minting (as a later step).

**Comment by diatomsRcool** [comment]
If we're going to get into things like cattle breeds, should we be looking to WikiData or WikiSpecies for authoritative CUIs?

**Comment by gaurav** [comment]
There is also an livestock breed ontology: https://www.ebi.ac.uk/ols/ontologies/lbo

**Comment by gaurav** [comment]
I've [updated the mapping file](https://docs.google.com/spreadsheets/d/1an0O7_Oc1lCfpO39G68benNj3NfijaxDoUTQ_vURZpk/edit) to include the CUI of the SNOMED term.

**Comment by gaurav** [comment]
I tried a different approach, using the [MRREL table](https://www.ncbi.nlm.nih.gov/books/NBK9685/#ch03.sec3.3.9) for parent/child relationships rather than the [MRHIER](https://www.ncbi.nlm.nih.gov/books/NBK9685/#ch03.sec3.3.11) table, and ended up with [exactly the same number of mappings](https://docs.google.com/spreadsheets/d/1QB9UjeugDShxQQ2ylt2toOXkoVcswFcCs5oX8wpnAs0/edit#gid=940458265).

@hsolbrig: I think you mentioned a few meetings ago that you were looking for the list of DICOM fields in which these terms were used? Any luck finding those? That could be useful in figuring out how best to map these terms to other ontologies.

**Comment by gaurav** [comment]
Minor update: I've updated my program to generate these mappings in the [SSSOM TSV format](https://github.com/OBOFoundry/SSSOM), now [available in our Google Drive](https://docs.google.com/spreadsheets/d/150n_mnD2ZNvHvv1lMIK1zIlfv91ttcgU3B0JDvpzbBI/edit). As before, we have 1849 (24.88%) SNOMED IDs in DICOM matched directly to NCI IDs, and 2625 IDs (35.32%) matched via their parent, out of a total of 7432 IDs. In addition, 219 SNOMED IDs were mapped to more than one NCI ID, which my program previously ignored -- for example, SNOMEDCT_US:2424003 (Soft tissue tumour, malignant) is mapped to NCI:C9306 (Soft Tissue Sarcoma), NCI:C4867 (Malignant Neoplasm of the Soft Tissue) and NCI:C9118 (Sarcoma of Soft Tissue and Bone).

My next step will be to see how many of the mapping gaps I can fill by using specific ontologies, such as the livestock breed ontology.

**Comment by gaurav** [comment]
We now have the exact terms from (in this order):
- The EBI [Ontology Lookup Service](https://www.ebi.ac.uk/ols/) 
- [Livestock Breed Ontology (LBO)](https://www.ebi.ac.uk/ols/ontologies/lbo)
- [Human Phenotype Ontology (HPO)](https://hpo.jax.org/app/)
- [Chemical Entities of Biological Interest (ChEBI)](https://www.ebi.ac.uk/chebi/)
 
This puts us at 2,434 terms remaining to be matched. You can see the [mappings in the SSSOM file](https://docs.google.com/spreadsheets/d/18luA05E9wLukOFamsRV3FWVnoCr57o8qAHe-aGYrPr8/edit#gid=1976835818).

My immediate next step is to see if we can group the remaining terms in some way, perhaps by looking at the hierarchical information in the NCImt. That might make it easier to figure out how to go about mapping the remaining terms. I'll also look into doing lexical matching.

**Comment by fedorov** [comment]
The SNOMED terms used in DICOM are captured in the context groups (search for "CID <number>") in this part of the standard: http://dicom.nema.org/medical/dicom/current/output/chtml/part16/PS3.16.html.

There is also an XML representation of the standard, and also if you look at the individual CID, you will see different representations resources for that table (see under "Resources" heading): http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_4.html#table_CID_4

I think some of those tables may contain a column with the matching NCIt term, but also many include the UMLS Concept Unique ID, so I think those mappings may be helpful to you, e.g., see http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_4.html#table_CID_4.

Note that DICOM is a live document! New SNOMED terms are included more or less regularly into it. I actually do not know what process was used to generate this content referenced in this comment from above https://github.com/cancerDHC/operations/issues/48#issuecomment-604480932, or what version of the standard was used to extract that list. It may well be incomplete or outdated. https://github.com/hsolbrig/SNOMEDToOWL/tree/master/test/data/dicom.

Going forward, when a new SNOMED term is added to DICOM, what would you like to see to help with the mapping task? Is UMLS Concept ID sufficient?

**Comment by gaurav** [comment]
Hi Andrey,

Thanks so much for your detailed response!

> The SNOMED terms used in DICOM are captured in the context groups (search for "CID ") in this part of the standard: http://dicom.nema.org/medical/dicom/current/output/chtml/part16/PS3.16.html.
> 
> There is also an XML representation of the standard, and also if you look at the individual CID, you will see different representations resources for that table (see under "Resources" heading): http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_4.html#table_CID_4
> 
> I think some of those tables may contain a column with the matching NCIt term, but also many include the UMLS Concept Unique ID, so I think those mappings may be helpful to you, e.g., see http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_4.html#table_CID_4.

We're actually not that interested in the UMLS Concept IDs, since the UMLS already contains a mapping of 30,350 SNOMED terms to UMLS concept identifiers. What we're trying to generate is a mapping from SNOMED identifiers to other well-defined identifiers, such as NCI Thesaurus identifiers or ontology terms. This would allow us to convert SNOMED identifiers (whether in DICOM files or any other resource) to identifiers that don't have the same usage restrictions as SNOMED, and whose hierarchical information we could use freely without restrictions. I'm don't think that's allowed with all SNOMED terms, but it should be permitted for the subset of 7,413 SNOMED terms that are covered by the [DICOM SNOMED agreement](https://www.snomed.org/SNOMED/media/SNOMED/documents/IHTSDO-DICOM-press-release_02032016-(1).pdf).

> Note that DICOM is a live document! New SNOMED terms are included more or less regularly into it. I actually do not know what process was used to generate this content referenced in this comment from above [#48 (comment)](https://github.com/cancerDHC/operations/issues/48#issuecomment-604480932) in https://github.com/hsolbrig/SNOMEDToOWL/tree/master/test/data/dicom, or what version of the standard was used to extract that list. It may well be incomplete or outdated.

I'm not sure where @hsolbrig got that list of SNOMED terms -- Harold, could you please let us know? However, it is 7,431 terms, which is exactly the number of SNOMED-in-DICOM terms mentioned in the agreement above. So this does seem to be the list of terms that we're allowed to use under the terms of the agreement.

> Going forward, when a new SNOMED term is added to DICOM, what would you like to see to help with the mapping task? Is UMLS Concept ID sufficient?

I think the only thing we would like is mappings from those new SNOMED terms to the NCI Thesaurus or to other ontologies. If anybody else thinks of something else that we might benefit from, please feel free to chime in!

**Comment by fedorov** [comment]
> However, it is 7,431 terms, which is exactly the number of SNOMED-in-DICOM terms mentioned in the agreement above. So this does seem to be the list of terms that we're allowed to use under the terms of the agreement.

Looking at [that agreement](https://www.snomed.org/SNOMED/media/SNOMED/documents/IHTSDO-DICOM-press-release_02032016-(1).pdf), since it is dated 2016, the list is most definitely outdated. There were most definitely SNOMED terms added to DICOM after 2016.

I wonder if @dclunie keeps track of the number of SNOMED terms in the latest version of the standard.

> I think the only thing we would like is mappings from those new SNOMED terms to the NCI Thesaurus or to other ontologies.

@dclunie how feasible would it be to have a recommendation to include mapping from SNOMED to  NCI Thesaurus or to other ontologies for the SNOMED terms that are added to the standard in the future?

**Comment by dclunie** [comment]
A couple of points about many of the issues discussed in this thread, including responses to Andrey's specific questions:

- The DICOM Subset of SNOMED CT concepts subject to our free use agreement (and now part of the SNOMED Global Patient Set (GPS)) is dynamic and not limited to the list in the PDF from the 2016 agreement

- We (DICOM) request additional codes from time to time, and the SNOMED CT maintenance process results in codes being inactivated, and we may or may not replace them with new ones; lately SNOMED's  substance/product and anatomy improvement initiatives have caused quite a lot of churn.

- There is no publicly shared resource at which resides a canonical list of those SNOMED CT concepts authorized for use in DICOM in a formal syntax; there is a REFSET accessible to those granted access, and I have been seeking permission to share it and a means to share it.

- I don't generally count the number of concepts in the current set, so there is nothing magic about "7,314" and we are beyond that number now; occasionally the SNOMED powers that be remind me not to ask for too many, per limits in the agreement.

- DICOM has permission (for its implementers and archived objects) to use retired inactivated codes, so in reality there are more codes than in the current subset that may be encountered in a DICOM context; so what is needed is the union of the current subset and anything listed in PS3.16 Annex J or O.

- I have scripts (XSL-T and bsh) that trawl the DocBook XML source of the standard to extract coded concepts used and filter them for those that are SCT or SRT identifiers, if anyone wants to reuse these (or their results); FYI I have attached an example run output for all coded concepts used in DICOM and those that are from SNOMED:

[snomedtuplesall_asof_20200705.txt.zip](https://github.com/cancerDHC/operations/files/5245735/snomedtuplesall_asof_20200705.txt.zip)
[alltuplesall_asof_20200705.txt.zip](https://github.com/cancerDHC/operations/files/5245736/alltuplesall_asof_20200705.txt.zip)

- The vast majority of SNOMED concepts listed in DICOM are not used in practice; the animal breeds are a case in point (only a few are relevant to preclinical research or routine veterinary practice), and a lot of these aren't in SNOMED CT anymore and have been handed off to another organization for maintenance.

- We include UMLS CUIs where known in the DICOM value sets (context groups) so that folks can get to one mapping that currently exists, and thence to other codes in other schemes if supported by UMLS (such as NCIt); note that many recently added/changed SCT codes are not yet in UMLS (but hopefully will be added)

- For the UMLS CUI listed in DICOM, sometimes there is ambiguity (more than one UMLS choice for an SCT code), so DICOM makes a choice since we only list one mapping; last time I did an automated run to populate these was in 2017, and here is the selected set (I assume you are not interested in the Java and XSL-T code that actually searched UMLS and made changes to the XML DocBook, but FYI it used MRCONSO_2016AB.RRF as the primary source):

[preselectedumls_asof_20171205.txt.zip](https://github.com/cancerDHC/operations/files/5245763/preselectedumls_asof_20171205.txt.zip)

- I don't think we want to start adding more mappings to the DICOM Standard itself (to NCIt or any other scheme), as opposed to relying on UMLS (or some other "authoritative" mapping, recognizing the many known limitations of UMLS); we do make occasional exceptions (e.g., for some anatomical value sets we add FMA or ICD11 topography or UBERON or species-specific (e.g., mouse) mapping); the corollary of this is that if you guys define new mappings from SNOMED CT to NCIt that are not already in UMLS, or are inconsistent with what is in UMLS, we (DICOM) would probably rather that you convinced UMLS to adopt them rather than having another place to go for them, or added them to DICOM as Andrey suggested.

- There are a lot of radiology/imaging-related concepts in RadLex that may be useful even though they are not listed/used in DICOM; these are free and while one may debate some of their choices, there has been a lot of thought put into them, including by those interested in ontologies; their anatomy is FMA-based; they are developing an OWL representation to replace the previous Protégé frame-based model; unfortunately they have been developed largely de novo and not mapped to SNOMED CT or NCIt or UMLS; the protagonists claim lack of resources/funding; I mention this not because IDC (or TCIA or DICOM) use RadLex a lot, but we do look at it whenever a new concept is needed (e.g., for standardized reporting of findings for some cancer types); same goes for radiomics (for which we use IBSI) just a reminder that there is more to imaging terminology than the subset of SNOMED CT that DICOM uses.

- Over the years the people involved in selecting SNOMED CT (or earlier version) concepts for a particular DICOM use-case have changed, as has their opinion/knowledge of SNOMED, so many of the selections may not be ideal (or indeed plain wrong); I mention this because sometimes you may find DICOM's choice of code meaning ("synonym") doesn't appear to match one of the SNOMED CT provided synonyms, and that when/if you encounter inconsistencies or errors please let us know so that we can improve the DICOM choice.

**Comment by gaurav** [comment]
Hi @dclunie, thanks so much for your detailed response and for the great resources you've provided!

> I have scripts (XSL-T and bsh) that trawl the DocBook XML source of the standard to extract coded concepts used and filter them for those that are SCT or SRT identifiers, if anyone wants to reuse these (or their results); FYI I have attached an example run output for all coded concepts used in DICOM and those that are from SNOMED:

This is really useful -- thanks so much for providing us with this list! I'm going to try to incorporate them in the workflow I've developed.

Are those scripts available online? I'd like to group these SNOMED terms in some way, and one way of doing that might be by identifying where in the standard they are mentioned.

> I don't think we want to start adding more mappings to the DICOM Standard itself (to NCIt or any other scheme), as opposed to relying on UMLS (or some other "authoritative" mapping, recognizing the many known limitations of UMLS)

That makes sense. I think our mappings are likely to be independent of the UMLS, at least initially -- we'll probably publish them as a list of mappings from SNOMED to NCIt and other identifiers, and leave it at that. 

> There are a lot of radiology/imaging-related concepts in RadLex that may be useful even though they are not listed/used in DICOM

Ooo, yes, I remember you mentioned RadLex when we spoke with IDC. I'll put it on my list of ontologies to map (https://github.com/cancerDHC/tools/issues/7).

**Comment by gaurav** [comment]
> The vast majority of SNOMED concepts listed in DICOM are not used in practice; the animal breeds are a case in point (only a few are relevant to preclinical research or routine veterinary practice), and a lot of these aren't in SNOMED CT anymore and have been handed off to another organization for maintenance.

That's a great point that not all SNOMED terms will be used very often in practice. Does IDC have information on how often each term is used? If not, would it make sense for us to go through the DICOM files in TCIA to look to try to collection some information on that?

**Comment by gaurav** [comment]
I've re-run my mapping and searching code with the list provided by @dclunie (I used the SCT entries but not the SRT entries, since I'm not sure how to map those to SNOMED identifiers yet). I found 9990 SNOMED CT entries, which [I have mapped](https://docs.google.com/spreadsheets/d/1UCndinOcR-tDshTzBnyyU4BMvpsR_2MD6Tou5_-PfwQ/edit#gid=645925580) with 5,348 exact matches (53.5%), 1,943 narrow matches (where we match a term to its parent term in the NCI Thesaurus, 19.5%), and 2,699 SNOMED terms without matches (27%).

Additional work on this mapping will be done in a couple of more specific issues:
- Include some additional ontologies, such as RadLex and AGROVOC (https://github.com/cancerDHC/tools/issues/19).
- Integrate search and mappings from BioPortal (https://github.com/cancerDHC/tools/issues/21).
- Group terms to get a better sense of what sort of terms are missing (https://github.com/cancerDHC/tools/issues/20).

**Comment by dclunie** [comment]
Very interesting, thanks.

Many (but not all) of the exact matches seem quite good (especially those based on UMLS commonality)

Those suggested by the EBI Ontology Lookup Service as exact matches, though many of them seem sound, sometimes don't seem "exact" after all so can't be trusted without manual curation. E.g., the matches between "abdominal structure" and "radiating chest pain in abdomen", or "abdominal artery" and "abdominal aorta artery", or "instrument, device", versus "patient-reported survey instrument").

There also seem to be some "substance" versus "method" matches from the EBI Ontology Lookup Service that are arguably incorrect, but which raise the problem that the "substance" in SNOMED doesn't really exist, e.g., "gram stain" is not really a substance at all, but a method that uses several substances in a series of steps (crystal violet, iodine, ethanol, safranin) - this is something we are working on in a separate DICOM project on staining description improvement.

I was interested to see that some of the SNOMED FMA anatomy matches were not apparently found in UMLS, even though the EBI Ontology Lookup Service matched them. Not sure if this has anything to do with DICOM's choice of "structure of" rather than "entire" SNOMED codes for anatomy (although I think UMLS matches the "structure of" rather than "entire" usually also). Or it may be that your UMLS search was for some reason incomplete. E.g., SCT:34625003 (structure of) "medial common iliac lymph node" maps to UMLS:C0229808, which maps to FMA:16641, which your matching did not pick up from UMLS, only EBO. This may be confounded by the node "group" concept in SNOMED and FMA (which DICOM does not use); i.e., SCT:245298008 "Medial common iliac lymph node group (body structure)" is also mapped to UMLS:C0229808 in the UMLS metathesaurus (and FMA:71820).

The narrow matches don't seem to serve much purpose (i.e., none of the narrow matches would be suitable replacements for what they match to) - how are you planning to use these?

The Livestock Breed Ontology (LBO) is very helpful - I wasn't aware that existed; not that many/any of the breed codes are actually used in DICOM implementations (they were a largely theoretical exercise when we added veterinary content).

By the way, there are many concepts in DICOM, some of which are commonly used, which do not come from SNOMED, and we couldn't find them in any other scheme (at least when we looked), and so DICOM created its own codes. See:

  [http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_D.html](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_D.html)

I periodically load these into Bioportal (even though the "ontology" is just a flat list with a single owl#Thing class parent):

  [http://bioportal.bioontology.org/ontologies/DCM](http://bioportal.bioontology.org/ontologies/DCM)

David

PS. I think it would be a good idea to try matching through the BioPortal (http://bioportal.bioontology.org/). It contains SNOMED, RadLex and FMA, as well as the DCM codes, and for some of those schemes, the entries also contain attributes that map to other schemes (e.g., in the case of SCT entries, UMLS CUIs). I have never tried its API, only its GUI, but for SCT:34625003 "medial common iliac lymph node, it finds the RadLex and FMA exact matches, for example.

PPS. Note that DICOM already contains UMLS mappings, which I think I mentioned before, e.g., for SCT:34625003 "medial common iliac lymph node", [http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_7600.html#para_cccbfe45-2286-4df6-bd5c-4dab6bc0ca49](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_7600.html#para_cccbfe45-2286-4df6-bd5c-4dab6bc0ca49). You may not want to use these directly, but you might want to check what you come up with, since we (DICOM) have already made resolution decisions when ambiguities occur.

**Comment by gaurav** [comment]
Just a quick update: based on David's suggestion, I've added support for [searching BioPortal](https://github.com/gaurav/umls-rrf-scala/pull/17), which includes terms from RadLex as well. You can see the results [in our shared Google Drive](https://docs.google.com/spreadsheets/d/1PPO-0hwLYI3HmA7rdyzZZqDrYj8hCJ1wW4qdbdKtpik/edit?usp=sharing) (search for "BioPortal" for BioPortal matches and "radlex.org" for RadLex terms). We even have six matches from the DCM "ontology" that David mentioned! Many of the BioPortal matches came from the [Ontology of Consumer Health Vocabulary (OCHV)](https://bioportal.bioontology.org/ontologies/OCHV) and the [Systematized Nomenclature of Medicine, International Version (SNMI)](http://bioportal.bioontology.org/ontologies/SNMI) and the [Interlinking Ontology for Biological Concepts (IOBC)](https://bioportal.bioontology.org/ontologies/IOBC/). We now have 1,710 terms remaining to map.

David: so sorry for my tardiness in replying to your previous comment! I am working on it and should be able to post a reply soon.

**Comment by gaurav** [comment]
Thanks again for your very detailed response, @dclunie!

> Those suggested by the EBI Ontology Lookup Service as exact matches, though many of them seem sound, sometimes don't seem "exact" after all so can't be trusted without manual curation. E.g., the matches between "abdominal structure" and "radiating chest pain in abdomen", or "abdominal artery" and "abdominal aorta artery", or "instrument, device", versus "patient-reported survey instrument").

Good point. We do need to figure out some way of identifying these errors without having to manually curate all of the mappings, such as by looking for cases where we've mapped one sort of thing against another sort of thing (such as the "substance" vs "method" matches you describe below). I've created an issue for tracking validating the DICOM SNOMED mappings at https://github.com/cancerDHC/tools/issues/24.

> There also seem to be some "substance" versus "method" matches from the EBI Ontology Lookup Service that are arguably incorrect, but which raise the problem that the "substance" in SNOMED doesn't really exist, e.g., "gram stain" is not really a substance at all, but a method that uses several substances in a series of steps (crystal violet, iodine, ethanol, safranin) - this is something we are working on in a separate DICOM project on staining description improvement.

That's a really good point! One thing we're working on that might help with this is grouping terms based on their hierarchy in NCImt or other ontologies (https://github.com/cancerDHC/tools/issues/20) -- we were planning to do this for the SNOMED terms only, but if we do this for both the subject and the object, we could identify cases where we've mapped a "substance" to a "method", or other similar discrepancies. 

> I was interested to see that some of the SNOMED FMA anatomy matches were not apparently found in UMLS, even though the EBI Ontology Lookup Service matched them. Not sure if this has anything to do with DICOM's choice of "structure of" rather than "entire" SNOMED codes for anatomy (although I think UMLS matches the "structure of" rather than "entire" usually also). Or it may be that your UMLS search was for some reason incomplete. E.g., SCT:34625003 (structure of) "medial common iliac lymph node" maps to UMLS:C0229808, which maps to FMA:16641, which your matching did not pick up from UMLS, only EBO. This may be confounded by the node "group" concept in SNOMED and FMA (which DICOM does not use); i.e., SCT:245298008 "Medial common iliac lymph node group (body structure)" is also mapped to UMLS:C0229808 in the UMLS metathesaurus (and FMA:71820).

Thanks for pointing this out! I've filed an issue to investigate this at https://github.com/cancerDHC/tools/issues/25. I'm hoping this is just because we were using the 2019 UMLS release and maybe it'll work once we switch over to the 2020 release, but if not, I'll dig into this and figure out what's going on there.

> The narrow matches don't seem to serve much purpose (i.e., none of the narrow matches would be suitable replacements for what they match to) - how are you planning to use these?

I don't think we want to use "narrow" matches (apparently, I got my terminology wrong, and these are actually supposed to be *broad* matches) to do any mappings. I think they're most useful as a way of grouping terms that we don't have an exact match for -- for instance, we find that we have 398 porcine species to match, 265 canine breeds to match, and so on. I think our goal is to eventually change all broad matches into exact matches.

> PS. I think it would be a good idea to try matching through the BioPortal (http://bioportal.bioontology.org/). It contains SNOMED, RadLex and FMA, as well as the DCM codes, and for some of those schemes, the entries also contain attributes that map to other schemes (e.g., in the case of SCT entries, UMLS CUIs). I have never tried its API, only its GUI, but for SCT:34625003 "medial common iliac lymph node, it finds the RadLex and FMA exact matches, for example.

Yes, this seems to have helped a lot -- thanks for the suggestion! I've gotten the BioPortal's exact-search API to work, but I'd like to try their mapping API as well (https://github.com/cancerDHC/tools/issues/21).

> PPS. Note that DICOM already contains UMLS mappings, which I think I mentioned before, e.g., for SCT:34625003 "medial common iliac lymph node", http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_7600.html#para_cccbfe45-2286-4df6-bd5c-4dab6bc0ca49. You may not want to use these directly, but you might want to check what you come up with, since we (DICOM) have already made resolution decisions when ambiguities occur.

That's a great idea! I've filed that as issue https://github.com/cancerDHC/tools/issues/23.

**Comment by monicacecilia** [comment]
Dependent on: 
- [ ] cancerDHC/tools#24
- [ ] cancerDHC/tools#20
- [ ] cancerDHC/tools#25
- [ ] cancerDHC/tools#21
- [ ] cancerDHC/tools#23

**Comment by monicacecilia** [comment]
@gaurav @balhoff - please share an update about this issue, and please indicate whether having closed https://github.com/cancerDHC/tools/issues/3 means that it can be resolved and closed or not. Thank you! 🌷

**Comment by monicacecilia** [comment]
The task described in the ticket was considered a test run for both vocabulary translation and the CCDH concierge services. In this regard, this task is completed in two (well, three) important ways:
1. We [built the code](https://github.com/cancerDHC/umls-rrf-scala) to pull relationships from UMLS, which we then used in building NCIt-Plus, and
2. We were the first workstream to use SSSOM to store term mappings, which I think led to the Terminology WS adopting them as well. SSSOM is pretty well established as the primary format for CCDH term mappings, despite occasional calls to look into something more sophisticated, [such as CTS-2 or OMOP](https://github.com/cancerDHC/tools/issues/3).
3. __Bonus achievement:__ we used this as a test-case to investigate Ptolemy.V, so now we have a pretty good idea about what’s good and what’s not about that tool.

As well, while this ticket describes activities and goals that where not linked to any specific project deliverables, existing development (of the [umls-rrf-scala tool](https://github.com/cancerDHC/umls-rrf-scala) and [SSSOM pipeline](https://github.com/mapping-commons/SSSOM)) have met the CCDH needs for this issue. 

While I am closing this ticket right now, we will consider reopening, or starting a new task, should the need for completing this mapping become critical for the successful delivery of the next Phase of CRDC-H. 

We kindly thank you for your contributions, and we continue to welcome your feedback. 

h/t @gaurav
