### ISSUE TITLE
1a2: Understand use cases

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/operations#7]
Understand the use cases driving the use of one resource by the other (i.e. the use of a terminology by an information model)

Depends on #6 
Terminologies use cases depend Depends on HOT user stories

**Comment by ShahimEssaid** [comment]
I think this needs clarification. A use case doesn't drive the use of a terminology by the information model. If anything, all use cases drive the whole model but even then the model is still somewhat independent of the use cases since it has a more semantic/ontological nature that is independent of the use cases but still aligned with the domain.

Looking at the other phase 1 tasks, this is the only one that talks about use cases. Maybe we can redefine this to be about the use cases themselves since they will be one input into the model/terminology development.

Sub tasks?

**Comment by nicolevasilevsky** [comment]
@DaveraGabriel developed and socialized the use of User Stories with the CCDH team.  The purpose for these stories are to develop shared understanding among diverse groups and provide a means to communicate with stakeholders about the utilization of work products in the context of the environment they serve. Additionally, beginning with User Stories is a method that can be employed to develop technical and functional requirements for tools development or adaptation for CCDH. We conducted an [online training workshop](https://docs.google.com/presentation/d/1qtIs677zEGf7lMaVOiKheQZpxk6dhvVLE-MJlOJVaQM/edit#slide=id.p1) on User Story Development for CCDH team members which [was recorded](https://github.com/cancerDHC/Terminology/blob/master/CCDH%20User%20Stories%20presentation%20playback.m3u).  This outlines User Story utility generically in the context of a software development process.  We developed a [framework](https://docs.google.com/spreadsheets/d/1MhblAat5UvPMKtcfOl9Nhk1vHzZEiKr6yjlQ8pM82yU/edit#gid=0) to identify User Story Actors and Use Case Scenarios for CCDH which leveraged [queries elicited from the client](https://docs.google.com/document/d/1hPXfyeUaaEPNcH-qbUIqiyIOwEN2rT6Oj_Ym_KQrSks/edit) for validation. This framework and analysis created is the basis for a [draft user story](https://docs.google.com/document/d/1-5_6qW77V48aQpOfyNZQJI5rTS0ASa-h/edit) for data uploaders as a project exemplar.  As a result of this preparatory work, development of User Stories which address the utilization of specific data annotation tools is in process.
